#########################################################
# DO Community Playbooks: mariadb on Debian 11
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Mise à jour des paquets
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Install mariadb server and client
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mariadb-server','mariadb-client','python3-pymysql']
      tags: [ system ]

   # Mariadb Configuration
   # - name: Personnalisation du compte root
   #   mysql_user:
   #     name: root
   #     password: "{{ mysql_root_password }}"
   #     login_unix_socket: /var/run/mysqld/mysqld.sock
   #   tags: [ mysql, mysql-root ]

    - name: Suppression des comptes anonymes
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root          #
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Suppression de la base de test
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creattion de la base de données 
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creattion de l'utilisateur associé
      mysql_user:
        name: "{{ mysql_user }}"
        host: "%"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]
      
      
    - name: Ouverture du socket ({{ mysql_bind_address }}:3306
      ini_file:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        section: mysqld
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: bind-address, value: "{{ mysql_bind_address }}" }
      tags: [ mysql ]
      
    - name: restart mariadb
      command: systemctl restart mariadb
      tags: [ mysql ]
        
